name: XmlLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lua-Format-Check:
    name: XML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: XML Lint
        uses: ChristophWurst/xmllint-action@v1.1
        with:
          xml-file: ./**/*.xml
